export const GET_PRODUCTS_SUCCESS= "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_ERROR= "GET_PRODUCTS_ERROR"
export const GET_PRODUCTS_REQUEST= "GET_PRODUCTS_REQUEST"



export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS"
export const ADD_NEW_PRODUCT_ERROR = "ADD_NEW_PRODUCT_ERROR"
export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST"
 

export const EDIT_PRODUCTS_REQUEST = "EDIT_PRODUCTS_REQUEST"
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR"
 

export const DEL_PRODUCT_SUCCESS = "DEL_PRODUCT_SUCCESS"
export const DEL_PRODUCT_ERROR="DEL_PRODUCT_ERROR"
export const DEL_PRODUCT_REQUEST = "DEL_PRODUCT_REQUEST"


 