// export const GET_REQUEST_PRODUCT = "GET_REQUEST_PRODUCT"
// export const GET_SUCCESS_PRODUCT = "GET_SUCCESS_PRODUCT"
// export const GET_FAIL_PRODUCT = "GET_FAIL_PRODUCT"



export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"

export const GET_MEN_PRODUCTS_REQUEST = "GET_MEN_PRODUCTS_REQUEST"
export const GET_MEN_PRODUCTS_SUCCESS = "GET_MEN_PRODUCTS_SUCCESS"
export const GET_MEN_PRODUCTS_FAILURE = "GET_MEN_PRODUCTS_FAILURE"

export const SELECT_PRODUCT = "SELECT_PRODUCT"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"

export const ADD_MEN_PRODUCTS_REQUEST = "ADD_MEN_PRODUCTS_REQUEST"
export const ADD_MEN_PRODUCTS_SUCCESS = "ADD_MEN_PRODUCTS_SUCCESS"
export const ADD_MEN_PRODUCTS_FAILURE = "ADD_MEN_PRODUCTS_FAILURE"

export const UPDATE_MEN_PRODUCTS_REQUEST = "UPDATE_MEN_PRODUCTS_REQUEST"
export const UPDATE_MEN_PRODUCTS_SUCCESS = "UPDATE_MEN_PRODUCTS_SUCCESS"
export const UPDATE_MEN_PRODUCTS_FAILURE = "UPDATE_MEN_PRODUCTS_FAILURE"

export const DELETE_MEN_PRODUCTS_REQUEST = "DELETE_MEN_PRODUCTS_REQUEST"
export const DELETE_MEN_PRODUCTS_SUCCESS = "DELETE_MEN_PRODUCTS_SUCCESS"
export const DELETE_MEN_PRODUCTS_FAILURE = "GET_MEN_PRODUCTS_FAILURE"

